- name: Install deps
  ansible.builtin.apt:
    lock_timeout: 240
    update_cache: true
    pkg:
      - ca-certificates
      - iptables-persistent
      - bird2
      - chrony

- name: Import the ssh_config role from the nycmesh.common collection
  ansible.builtin.import_role:
    name: nycmesh.common.ssh_config

- name: Bird systemd unit
  ansible.builtin.copy:
    src: bird.service
    dest: /lib/systemd/system/bird.service
    mode: "0644"

- name: Allow restarting of chrony
  ansible.builtin.lineinfile:
    path: /lib/systemd/system/chrony.service
    insertafter: '\[Service\]'
    search_string: Restart=
    line: "Restart=always"

- name: Import the Datadog Agent role from the Datadog collection
  ansible.builtin.import_role:
    name: datadog.dd.agent
  vars:
    datadog_api_key: "{{ DATADOG_API_KEY }}"
    datadog_site: "{{ DATADOG_SITE }}"
    datadog_config:
      hostname: "{{ VM_HOSTNAME }}"
      logs_enabled: true
    datadog_additional_groups: "systemd-journal"
    datadog_checks:
      journald:
        logs:
          - type: journald
            path: /var/log/journal/

- name: Reload datadog
  ansible.builtin.systemd_service:
    name: datadog-agent
    state: restarted
    enabled: true
    daemon_reload: true

- name: Netplan dummy0 interface
  ansible.builtin.template:
    src: netplan_dummy0.yaml.j2
    dest: /etc/netplan/dummy0.yaml
    mode: "600"

- name: Netplan dummy1 interface
  ansible.builtin.template:
    src: netplan_dummy1.yaml.j2
    dest: /etc/netplan/dummy1.yaml
    mode: "600"

- name: Iptables rules
  ansible.builtin.template:
    src: iptables.j2
    dest: /etc/iptables/rules.v4
    mode: "600"

- name: Restore iptables rules
  ansible.builtin.command:
    cmd: "bash -c '/sbin/iptables-restore < /etc/iptables/rules.v4'"
    creates: /tmp/fake_for_linter

- name: Netplan apply
  ansible.builtin.command:
    cmd: "bash -c 'netplan apply && touch /tmp/netplan_applied'"
    creates: /tmp/netplan_applied

- name: Restart and enable iptables service
  ansible.builtin.service:
    name: netfilter-persistent
    state: restarted
    enabled: true

- name: Chrony config
  ansible.builtin.template:
    src: chrony.conf.j2
    dest: /etc/chrony/chrony.conf
    mode: "0644"

- name: Chrony sources
  ansible.builtin.copy:
    src: configured_servers.sources
    dest: /etc/chrony/sources.d/configured_servers.sources
    mode: "0644"

- name: Restart chrony
  ansible.builtin.systemd_service:
    name: chrony
    state: restarted
    enabled: true

- name: Bird config
  ansible.builtin.template:
    src: bird.conf.j2
    dest: /etc/bird/bird.conf
    mode: "640"
    owner: "bird"
    group: "bird"

- name: Reload bird
  ansible.builtin.systemd_service:
    name: bird
    state: reloaded
    enabled: true
