name: Deploy Environments
permissions: read-all

on:
  push:
    branches:
      - main
      - james/init
  workflow_dispatch:
    branches:
      - main

jobs:
  deploy_prod2:
    name: Deploy prod2
    uses: ./.github/workflows/deploy_ntp.yaml
    with:
      environment: prod2
    secrets: inherit
    #if: github.ref == 'refs/heads/main'

  deploy_prod3:
    name: Deploy prod3
    uses: ./.github/workflows/deploy_ntp.yaml
    with:
      environment: prod3
    secrets: inherit
    needs: deploy_prod2
    #if: github.ref == 'refs/heads/main'
